mappings:
  SecureEditableFileField: SilverStripe\UserForms\Extension\SecureEditableFileField
  UserFormFieldEditorExtension: SilverStripe\UserForms\Extension\UserFormFieldEditorExtension
  UserFormValidator: SilverStripe\UserForms\Extension\UserFormValidator
  GridFieldAddClassesButton: SilverStripe\UserForms\Form\GridFieldAddClassesButton
  UserForm: SilverStripe\UserForms\Form\UserForm
  UserFormsGridFieldFilterHeader: SilverStripe\UserForms\Form\UserFormsGridFieldFilterHeader
  UserFormsCheckboxSetField: SilverStripe\UserForms\FormField\UserFormsCheckboxSetField
  UserFormsCompositeField: SilverStripe\UserForms\FormField\UserFormsCompositeField
  UserFormsFieldContainer: SilverStripe\UserForms\FormField\UserFormsFieldContainer
  UserFormsFieldList: SilverStripe\UserForms\FormField\UserFormsFieldList
  UserFormsGroupField: SilverStripe\UserForms\FormField\UserFormsGroupField
  UserFormsStepField: SilverStripe\UserForms\FormField\UserFormsStepField
  EditableCustomRule: SilverStripe\UserForms\Model\EditableCustomRule
  UserDefinedForm: SilverStripe\UserForms\Model\UserDefinedForm
  UserDefinedFormController: SilverStripe\UserForms\Model\UserDefinedFormController
  EditableCheckbox: SilverStripe\UserForms\Model\EditableFormField\EditableCheckbox
  EditableCheckboxGroupField: SilverStripe\UserForms\Model\EditableFormField\EditableCheckboxGroupField
  EditableCountryDropdownField: SilverStripe\UserForms\Model\EditableFormField\EditableCountryDropdownField
  EditableDateField: SilverStripe\UserForms\Model\EditableFormField\EditableDateField
  EditableDateField_FormField: SilverStripe\UserForms\Model\EditableFormField\EditableDateField\FormField
  EditableDropdown: SilverStripe\UserForms\Model\EditableFormField\EditableDropdown
  EditableEmailField: SilverStripe\UserForms\Model\EditableFormField\EditableEmailField
  EditableFieldGroup: SilverStripe\UserForms\Model\EditableFormField\EditableFieldGroup
  EditableFieldGroupEnd: SilverStripe\UserForms\Model\EditableFormField\EditableFieldGroupEnd
  EditableFileField: SilverStripe\UserForms\Model\EditableFormField\EditableFileField
  EditableFormField: SilverStripe\UserForms\Model\EditableFormField
  EditableFormFieldValidator: SilverStripe\UserForms\Model\EditableFormField\Validator
  EditableFormHeading: SilverStripe\UserForms\Model\EditableFormField\EditableFormHeading
  EditableFormStep: SilverStripe\UserForms\Model\EditableFormField\EditableFormStep
  EditableLiteralField: SilverStripe\UserForms\Model\EditableFormField\EditableLiteralField
  EditableMemberListField: SilverStripe\UserForms\Model\EditableFormField\EditableMemberListField
  EditableMultipleOptionField: SilverStripe\UserForms\Model\EditableFormField\EditableMultipleOptionField
  EditableNumericField: SilverStripe\UserForms\Model\EditableFormField\EditableNumericField
  EditableOption: SilverStripe\UserForms\Model\EditableFormField\EditableOption
  EditableRadioField: SilverStripe\UserForms\Model\EditableFormField\EditableRadioField
  EditableTextField: SilverStripe\UserForms\Model\EditableFormField\EditableTextField
  UserDefinedForm_EmailRecipient: SilverStripe\UserForms\Model\Recipient\EmailRecipient
  UserDefinedForm_EmailRecipientCondition: SilverStripe\UserForms\Model\Recipient\EmailRecipientCondition
  UserFormRecipientEmail: SilverStripe\UserForms\Model\Recipient\UserFormRecipientEmail
  UserFormRecipientItemRequest: SilverStripe\UserForms\Model\Recipient\UserFormRecipientItemRequest
  SubmittedFileField: SilverStripe\UserForms\Model\Submission\SubmittedFileField
  SubmittedForm: SilverStripe\UserForms\Model\Submission\SubmittedForm
  SubmittedFormField: SilverStripe\UserForms\Model\Submission\SubmittedFormField
  DisambiguationSegmentFieldModifier: SilverStripe\UserForms\Modifier\DisambiguationSegmentFieldModifier
  UnderscoreSegmentFieldModifier: SilverStripe\UserForms\Modifier\UnderscoreSegmentFieldModifier
  UserFormsColumnCleanTask: SilverStripe\UserForms\Task\UserFormsColumnCleanTask
  UserFormsUpgradeService: SilverStripe\UserForms\Task\UserFormsUpgradeService
  UserFormsUpgradeTask: SilverStripe\UserForms\Task\UserFormsUpgradeTask
  UserFormsVersionedTask: SilverStripe\UserForms\Task\UserFormsVersionedTask
  UserFormTest: SilverStripe\UserForms\Test\Form\UserFormTest
  UserFormsCheckboxSetFieldTest: SilverStripe\UserForms\Test\FormField\UserFormsCheckboxSetFieldTest
  EditableCustomRuleTest: SilverStripe\UserForms\Test\Model\EditableCustomRuleTest
  UserDefinedFormControllerTest: SilverStripe\UserForms\Test\Model\UserDefinedFormControllerTest
  UserDefinedFormControllerTest_Controller: SilverStripe\UserForms\Test\Model\UserDefinedFormControllerTest_Controller
  UserDefinedFormTest: SilverStripe\UserForms\Test\Model\UserDefinedFormTest
  EditableDropdownTest: SilverStripe\UserForms\Test\Model\EditableFormField\EditableDropdownTest
  EditableFileFieldTest: SilverStripe\UserForms\Test\Model\EditableFormField\EditableFileFieldTest
  EditableFormFieldTest: SilverStripe\UserForms\Test\Model\EditableFormField\EditableFormFieldTest
  EditableLiteralFieldTest: SilverStripe\UserForms\Test\Model\EditableFormField\EditableLiteralFieldTest
  SecureEditableFileFieldTest: SilverStripe\UserForms\Test\Model\EditableFormField\SecureEditableFileFieldTest
  UserDefinedForm_EmailRecipientConditionTest: SilverStripe\UserForms\Test\Model\Recipient\UserDefinedForm_EmailRecipientConditionTest
  UserFormsUpgradeServiceTest: SilverStripe\UserForms\Test\Task\UserFormsUpgradeServiceTest
  UserFormsVersionedTaskTest: SilverStripe\UserForms\Test\Task\UserFormsVersionedTaskTest
